using System.Collections.Generic;
using UnityEngine;

public static class AgentDataRegistry {

    private static List<string> firstNamesMale = new List<string>();
    private static List<string> firstNamesFemale = new List<string>();
    private static List<string> firstNamesNeutral = new List<string>();
    private static List<string> firstNamesAll = new List<string>();
    private static List<string> lastNames = new List<string>();
    
    
    private static WeightedRegistry genderRegistry = new WeightedRegistry();
    private static WeightedRegistry professionRegistry = new WeightedRegistry();


    public static void Initialize() {
        Gender.InitializeList();
        Profession.InitializeList();

        InitializeFirstNames();
        InitializeLastNames();
        
        //Weighted Age
        
        
        //Weighted gender
        List<Gender> genderList = Gender.GetList();
        for (int i = 0; i < genderList.Count; i++) {
            genderRegistry.AddToList(new WeightedOption(genderList[i].GetWeight(), genderList[i].name));
        }
        
        //Weighted profession
        List<Profession> professionList = Profession.GetList();
        for (int i = 0; i < professionList.Count; i++) {
            professionRegistry.AddToList(new WeightedOption(professionList[i].GetWeight(), professionList[i].name));
        }
        
        Debug.Log($"Agent data registry created with {firstNamesAll.Count} first names, {lastNames.Count} last names, {genderRegistry.GetListSize()} genders and {professionRegistry.GetListSize()} professions");
    }

    public static AgentDataObject CreateAgentData() {
        string firstName;
        string lastName = lastNames[Random.Range(0, lastNames.Count)];

        Gender gender = Gender.GetGender(genderRegistry.GetWeightedRandomItem().GetName());
        Profession profession = Profession.GetProfession(professionRegistry.GetWeightedRandomItem().GetName());
        WeightedRegistry ageReg = new WeightedRegistry();

        if (profession.GetProfession() == EnumProfession.STUDENT) {
            ageReg.AddToList(new WeightedOption(50.0f, 18));
            ageReg.AddToList(new WeightedOption(40.0f, 19));
            ageReg.AddToList(new WeightedOption(30.0f, 20));
            ageReg.AddToList(new WeightedOption(20.0f, 21));
            ageReg.AddToList(new WeightedOption(10.0f, 22));
            ageReg.AddToList(new WeightedOption(5.0f, 23));
            ageReg.AddToList(new WeightedOption(5.0f, 24));
            ageReg.AddToList(new WeightedOption(5.0f, 25));
            ageReg.AddToList(new WeightedOption(5.0f, 26));
            ageReg.AddToList(new WeightedOption(5.0f, 27));
            for (int i = 28; i < 50; i++) {
                ageReg.AddToList(new WeightedOption(6.0f - i*0.1f, i));
            }
        } else if (profession.GetProfession() == EnumProfession.RETIRED) { //maybe the saddest code I've ever written. Older = less chance to exist.
            for (int i = 65; i < 95; i++) {
                float modifier = 0.1f;
                if (i > 75) modifier = 0.2f;
                if (i > 85) modifier = 0.3f;
                ageReg.AddToList(new WeightedOption(10.0f - (i-60)*modifier, i));
            }
        } else {
            for (int i = 21; i < 65; i++) {
                //Linear peak to have the most amount of NPCs age 35
                float modifier = i * 0.1f;
                if (i >= 35) {
                    modifier = (35 - i) * 0.1f + 3.5f;
                }
                
                ageReg.AddToList(new WeightedOption(10.0f - (i-60)*modifier, i));
            }
        }
        
        int age = ageReg.GetWeightedRandomItem().GetOption();

        if (gender.GetGender() == EnumGender.MALE) {
            firstName = firstNamesMale[Random.Range(0, firstNamesMale.Count)];
        } else if (gender.GetGender() == EnumGender.FEMALE) {
            firstName = firstNamesFemale[Random.Range(0, firstNamesFemale.Count)];
        }
        else {
            firstName = firstNamesAll[Random.Range(0, firstNamesAll.Count)];
        }

        return new AgentDataObject(firstName, lastName, age, gender, profession);
    }

    //Just some really long lists of names below here. End of the class :)
    //Name list source:
    //First names male: Top ~150 from https://www.goodhousekeeping.com/life/parenting/a37641039/top-baby-boy-names/ plus some friends etc
    //First names female: Top ~150 from https://www.verywellfamily.com/top-1000-baby-girl-names-2757832 plus friends
    //First names neutral: https://www.whattoexpect.com/baby-names/unisex-baby-names/ 
    //First names gender-non-conforming: People I know/facebook groups
    private static void InitializeFirstNames() {
        #region MALE_NAMES
        firstNamesMale.Add("Aaron");
        firstNamesMale.Add("Adam");
        firstNamesMale.Add("Adrian");
        firstNamesMale.Add("Adriel");
        firstNamesMale.Add("Aiden");
        firstNamesMale.Add("Alexander");
        firstNamesMale.Add("Amir");
        firstNamesMale.Add("Andrew");
        firstNamesMale.Add("Angel");
        firstNamesMale.Add("Anthony");
        firstNamesMale.Add("Ashton");
        firstNamesMale.Add("Austin");
        firstNamesMale.Add("Axel");
        firstNamesMale.Add("Ayden");
        firstNamesMale.Add("Benjamin");
        firstNamesMale.Add("Bennett");
        firstNamesMale.Add("Bentley");
        firstNamesMale.Add("Caleb");
        firstNamesMale.Add("Calvin");
        firstNamesMale.Add("Cameron");
        firstNamesMale.Add("Carlos");
        firstNamesMale.Add("Carson");
        firstNamesMale.Add("Carter");
        firstNamesMale.Add("Charles");
        firstNamesMale.Add("Chase");
        firstNamesMale.Add("Christian");
        firstNamesMale.Add("Christopher");
        firstNamesMale.Add("Chris");
        firstNamesMale.Add("Cole");
        firstNamesMale.Add("Connor");
        firstNamesMale.Add("Cooper");
        firstNamesMale.Add("Dakota");
        firstNamesMale.Add("Damian");
        firstNamesMale.Add("Daniel");
        firstNamesMale.Add("David");
        firstNamesMale.Add("Diego");
        firstNamesMale.Add("Dominic");
        firstNamesMale.Add("Dylan");
        firstNamesMale.Add("Easton");
        firstNamesMale.Add("Eli");
        firstNamesMale.Add("Elias");
        firstNamesMale.Add("Elijah");
        firstNamesMale.Add("Emmanuel");
        firstNamesMale.Add("Emmett");
        firstNamesMale.Add("Ethan");
        firstNamesMale.Add("Evan");
        firstNamesMale.Add("Everett");
        firstNamesMale.Add("Ezekiel");
        firstNamesMale.Add("Ezra");
        firstNamesMale.Add("Gabriel");
        firstNamesMale.Add("Gael");
        firstNamesMale.Add("Gavin");
        firstNamesMale.Add("George");
        firstNamesMale.Add("Giovanni");
        firstNamesMale.Add("Grayson");
        firstNamesMale.Add("Greyson");
        firstNamesMale.Add("Harrison");
        firstNamesMale.Add("Henry");
        firstNamesMale.Add("Hudson");
        firstNamesMale.Add("Ian");
        firstNamesMale.Add("Ioannis");
        firstNamesMale.Add("Isaac");
        firstNamesMale.Add("Isaiah");
        firstNamesMale.Add("Jace");
        firstNamesMale.Add("Jack");
        firstNamesMale.Add("Jackson");
        firstNamesMale.Add("Jacob");
        firstNamesMale.Add("James");
        firstNamesMale.Add("Jameson");
        firstNamesMale.Add("Jason");
        firstNamesMale.Add("Jasper");
        firstNamesMale.Add("Jeremiah");
        firstNamesMale.Add("Jethro");
        firstNamesMale.Add("John");
        firstNamesMale.Add("Jonah");
        firstNamesMale.Add("Jonathan");
        firstNamesMale.Add("Jose");
        firstNamesMale.Add("Joseph");
        firstNamesMale.Add("Joshua");
        firstNamesMale.Add("Josiah");
        firstNamesMale.Add("Juan");
        firstNamesMale.Add("Julian");
        firstNamesMale.Add("Kingston");
        firstNamesMale.Add("Landon");
        firstNamesMale.Add("Legend");
        firstNamesMale.Add("Leo");
        firstNamesMale.Add("Leonardo");
        firstNamesMale.Add("Liam");
        firstNamesMale.Add("Lincoln");
        firstNamesMale.Add("Logan");
        firstNamesMale.Add("Luca");
        firstNamesMale.Add("Lucas");
        firstNamesMale.Add("Luis");
        firstNamesMale.Add("Luke");
        firstNamesMale.Add("Mason");
        firstNamesMale.Add("Mateo");
        firstNamesMale.Add("Matthew");
        firstNamesMale.Add("Maverick");
        firstNamesMale.Add("Max");
        firstNamesMale.Add("Micah");
        firstNamesMale.Add("Michael");
        firstNamesMale.Add("Miles");
        firstNamesMale.Add("Milo");
        firstNamesMale.Add("Nathan");
        firstNamesMale.Add("Nathaniel");
        firstNamesMale.Add("Nicholas");
        firstNamesMale.Add("Noah");
        firstNamesMale.Add("Nolan");
        firstNamesMale.Add("Oliver");
        firstNamesMale.Add("Owen");
        firstNamesMale.Add("Parker");
        firstNamesMale.Add("River");
        firstNamesMale.Add("Robert");
        firstNamesMale.Add("Roman");
        firstNamesMale.Add("Rowan");
        firstNamesMale.Add("Ryan");
        firstNamesMale.Add("Salim");
        firstNamesMale.Add("Samuel");
        firstNamesMale.Add("Sawyer");
        firstNamesMale.Add("Sebastian");
        firstNamesMale.Add("Silas");
        firstNamesMale.Add("Theodore");
        firstNamesMale.Add("Thomas");
        firstNamesMale.Add("Tyler");
        firstNamesMale.Add("Vincent");
        firstNamesMale.Add("Wesley");
        firstNamesMale.Add("Weston");
        firstNamesMale.Add("William");
        firstNamesMale.Add("Xander");
        firstNamesMale.Add("Zachary");
        firstNamesMale.Add("Zion");
        #endregion
        #region FEMALE_NAMES
        firstNamesFemale.Add("Abigail");
        firstNamesFemale.Add("Addison");
        firstNamesFemale.Add("Adeline");
        firstNamesFemale.Add("Alaia");
        firstNamesFemale.Add("Alexandra");
        firstNamesFemale.Add("Alexa");
        firstNamesFemale.Add("Alice");
        firstNamesFemale.Add("Allison");
        firstNamesFemale.Add("Amara");
        firstNamesFemale.Add("Amaya");
        firstNamesFemale.Add("Amelia");
        firstNamesFemale.Add("Andrea");
        firstNamesFemale.Add("Anna");
        firstNamesFemale.Add("Aria");
        firstNamesFemale.Add("Ariana");
        firstNamesFemale.Add("Arya");
        firstNamesFemale.Add("Athena");
        firstNamesFemale.Add("Aubrey");
        firstNamesFemale.Add("Audrey");
        firstNamesFemale.Add("Aurora");
        firstNamesFemale.Add("Autumn");
        firstNamesFemale.Add("Ava");
        firstNamesFemale.Add("Ayla");
        firstNamesFemale.Add("Bella");
        firstNamesFemale.Add("Brianna");
        firstNamesFemale.Add("Brielle");
        firstNamesFemale.Add("Camila");
        firstNamesFemale.Add("Caroline");
        firstNamesFemale.Add("Cecilia");
        firstNamesFemale.Add("Charlotte");
        firstNamesFemale.Add("Chloe");
        firstNamesFemale.Add("Claire");
        firstNamesFemale.Add("Clara");
        firstNamesFemale.Add("Cora");
        firstNamesFemale.Add("Daisy");
        firstNamesFemale.Add("Delilah");
        firstNamesFemale.Add("Eden");
        firstNamesFemale.Add("Eleanor");
        firstNamesFemale.Add("Elena");
        firstNamesFemale.Add("Eliana");
        firstNamesFemale.Add("Eliza");
        firstNamesFemale.Add("Elizabeth");
        firstNamesFemale.Add("Ella");
        firstNamesFemale.Add("Elliana");
        firstNamesFemale.Add("Ellie");
        firstNamesFemale.Add("Eloise");
        firstNamesFemale.Add("Emery");
        firstNamesFemale.Add("Emilia");
        firstNamesFemale.Add("Emily");
        firstNamesFemale.Add("Emma");
        firstNamesFemale.Add("Eva");
        firstNamesFemale.Add("Evelyn");
        firstNamesFemale.Add("Everly");
        firstNamesFemale.Add("Faith");
        firstNamesFemale.Add("Gabriella");
        firstNamesFemale.Add("Genesis");
        firstNamesFemale.Add("Gianna");
        firstNamesFemale.Add("Grace");
        firstNamesFemale.Add("Hadley");
        firstNamesFemale.Add("Hailey");
        firstNamesFemale.Add("Hannah");
        firstNamesFemale.Add("Harper");
        firstNamesFemale.Add("Hazel");
        firstNamesFemale.Add("Iris");
        firstNamesFemale.Add("Isabella");
        firstNamesFemale.Add("Isabelle");
        firstNamesFemale.Add("Issy");
        firstNamesFemale.Add("Isla");
        firstNamesFemale.Add("Ivy");
        firstNamesFemale.Add("Jade");
        firstNamesFemale.Add("Jasmine");
        firstNamesFemale.Add("Josephine");
        firstNamesFemale.Add("Josie");
        firstNamesFemale.Add("Julia");
        firstNamesFemale.Add("Katherine");
        firstNamesFemale.Add("Kayley");
        firstNamesFemale.Add("Layla");
        firstNamesFemale.Add("Leah");
        firstNamesFemale.Add("Leilani");
        firstNamesFemale.Add("Liliana");
        firstNamesFemale.Add("Lillian");
        firstNamesFemale.Add("Lily");
        firstNamesFemale.Add("Lucy");
        firstNamesFemale.Add("Luna");
        firstNamesFemale.Add("Lydia");
        firstNamesFemale.Add("Lyla");
        firstNamesFemale.Add("Margaret");
        firstNamesFemale.Add("Maria");
        firstNamesFemale.Add("Mary");
        firstNamesFemale.Add("Maya");
        firstNamesFemale.Add("Melanie");
        firstNamesFemale.Add("Mia");
        firstNamesFemale.Add("Mila");
        firstNamesFemale.Add("Naomi");
        firstNamesFemale.Add("Natalia");
        firstNamesFemale.Add("Natalie");
        firstNamesFemale.Add("Nora");
        firstNamesFemale.Add("Olivia");
        firstNamesFemale.Add("Paisley");
        firstNamesFemale.Add("Parker");
        firstNamesFemale.Add("Penelope");
        firstNamesFemale.Add("Piper");
        firstNamesFemale.Add("Reagan");
        firstNamesFemale.Add("Reese");
        firstNamesFemale.Add("Ruya");
        firstNamesFemale.Add("Riley");
        firstNamesFemale.Add("Rose");
        firstNamesFemale.Add("Ruby");
        firstNamesFemale.Add("Sadie");
        firstNamesFemale.Add("Samantha");
        firstNamesFemale.Add("Sarah");
        firstNamesFemale.Add("Saskia");
        firstNamesFemale.Add("Savannah");
        firstNamesFemale.Add("Scarlett");
        firstNamesFemale.Add("Serenity");
        firstNamesFemale.Add("Skylar");
        firstNamesFemale.Add("Sofia");
        firstNamesFemale.Add("Sophie");
        firstNamesFemale.Add("Stella");
        firstNamesFemale.Add("Summer");
        firstNamesFemale.Add("Valentina");
        firstNamesFemale.Add("Valerie");
        firstNamesFemale.Add("Victoria");
        firstNamesFemale.Add("Violet");
        firstNamesFemale.Add("Vivian");
        firstNamesFemale.Add("Willow");
        firstNamesFemale.Add("Zoe");
        #endregion
        #region NEUTRAL_NAMES
        firstNamesNeutral.Add("Aeryn");
        firstNamesNeutral.Add("Alex");
        firstNamesNeutral.Add("Avery");
        firstNamesNeutral.Add("Charlie");
        firstNamesNeutral.Add("Jayden");
        firstNamesNeutral.Add("Jordan");
        firstNamesNeutral.Add("Ren");
        firstNamesNeutral.Add("Taylor");
        firstNamesNeutral.Add("Asher");
        firstNamesNeutral.Add("Aris");
        firstNamesNeutral.Add("Scout");
        firstNamesNeutral.Add("Killian");
        firstNamesNeutral.Add("Quinn");
        firstNamesNeutral.Add("Lex");
        firstNamesNeutral.Add("Levi");
        firstNamesNeutral.Add("Lux");
        firstNamesNeutral.Add("Kove");
        firstNamesNeutral.Add("Finn");
        firstNamesNeutral.Add("Wren");
        firstNamesNeutral.Add("Kione");
        firstNamesNeutral.Add("Kade");
        firstNamesNeutral.Add("Remi");
        firstNamesNeutral.Add("Len");
        firstNamesNeutral.Add("Keid");
        firstNamesNeutral.Add("Pleione");
        firstNamesNeutral.Add("Alder");
        firstNamesNeutral.Add("Kit");
        firstNamesNeutral.Add("Cerise");
        firstNamesNeutral.Add("Antares");
        firstNamesNeutral.Add("Probli");
        firstNamesNeutral.Add("Cassowary");
        firstNamesNeutral.Add("Kai");
        firstNamesNeutral.Add("Echo");
        firstNamesNeutral.Add("Onyx");
        firstNamesNeutral.Add("Nova");
        firstNamesNeutral.Add("Link");
        firstNamesNeutral.Add("Kat");
        firstNamesNeutral.Add("Ryn");
        firstNamesNeutral.Add("Hayl");
        firstNamesNeutral.Add("Toma");
        firstNamesNeutral.Add("Lylle");
        firstNamesNeutral.Add("Zaidi");
        firstNamesNeutral.Add("Phoenix");
        firstNamesNeutral.Add("Andromeda");
        firstNamesNeutral.Add("Fennec");
        firstNamesNeutral.Add("Ronan");
        firstNamesNeutral.Add("Leto");
        firstNamesNeutral.Add("Shay");
        firstNamesNeutral.Add("Arden");
        firstNamesNeutral.Add("Jinx");
        firstNamesNeutral.Add("Rogue");
        firstNamesNeutral.Add("Orion");
        #endregion
        
        for (int i = 0; i < firstNamesMale.Count; i++) { firstNamesAll.Add(firstNamesMale[i]); }
        for (int i = 0; i < firstNamesFemale.Count; i++) { firstNamesAll.Add(firstNamesFemale[i]); }

        for (int i = 0; i < firstNamesNeutral.Count; i++) {
            firstNamesMale.Add(firstNamesNeutral[i]);
            firstNamesFemale.Add(firstNamesNeutral[i]);
            firstNamesAll.Add(firstNamesNeutral[i]);
        }

        #region GNC_NAMES
        //Traditional non-binary names aren't added to neutral list and won't be applied to cisgender character
        firstNamesAll.Add("Socks");
        firstNamesAll.Add("River");
        firstNamesAll.Add("Terran");
        firstNamesAll.Add("Wildon");
        firstNamesAll.Add("Faux");
        firstNamesAll.Add("Vale");
        firstNamesAll.Add("Muse");
        firstNamesAll.Add("Grey");
        firstNamesAll.Add("Gryph");
        firstNamesAll.Add("Legion");
        firstNamesAll.Add("Hedgehog");
        firstNamesAll.Add("Moth");
        firstNamesAll.Add("Mouse");
        firstNamesAll.Add("Urano");
        firstNamesAll.Add("Fern");
        firstNamesAll.Add("Human");
        firstNamesAll.Add("Kolya");
        firstNamesAll.Add("Sky");
        firstNamesAll.Add("Petrichor");
        firstNamesAll.Add("Zephyr");
        firstNamesAll.Add("Pigeon");
        firstNamesAll.Add("Frost");
        firstNamesAll.Add("Caution"); //from my research post, "Caution, this person is clearly fae". Thats a name now. Thanks person.
        firstNamesAll.Add("Bluejay");
        firstNamesAll.Add("Corvus");
        firstNamesAll.Add("Brick");
        firstNamesAll.Add("Toast");
        firstNamesAll.Add("Stick");
        firstNamesAll.Add("Leaf");
        firstNamesAll.Add("Pebble");
        firstNamesAll.Add("Ghost");
        firstNamesAll.Add("Lua");
        firstNamesAll.Add("Sope");
        firstNamesAll.Add("Star");
        firstNamesAll.Add("Rain");
        firstNamesAll.Add("Bug");
        firstNamesAll.Add("Neelix");
        firstNamesAll.Add("Moon");
        firstNamesAll.Add("Blue");
        firstNamesAll.Add("Stone");
        #endregion
    }

    private static void InitializeLastNames() {
        #region LAST_NAMES
        lastNames.Add("Acosta");
        lastNames.Add("Adams");
        lastNames.Add("Adkins");
        lastNames.Add("Aguilar");
        lastNames.Add("Aguirre");
        lastNames.Add("Alexander");
        lastNames.Add("Allen");
        lastNames.Add("Alvarado");
        lastNames.Add("Alvarez");
        lastNames.Add("Anderson");
        lastNames.Add("Andrews");
        lastNames.Add("Armstrong");
        lastNames.Add("Arnold");
        lastNames.Add("Austin");
        lastNames.Add("Avila");
        lastNames.Add("Ayala");
        lastNames.Add("Bailey");
        lastNames.Add("Baker");
        lastNames.Add("Baldwin");
        lastNames.Add("Banks");
        lastNames.Add("Barber");
        lastNames.Add("Barker");
        lastNames.Add("Barnes");
        lastNames.Add("Barnett");
        lastNames.Add("Barrett");
        lastNames.Add("Barton");
        lastNames.Add("Bates");
        lastNames.Add("Beck");
        lastNames.Add("Becker");
        lastNames.Add("Bell");
        lastNames.Add("Bennett");
        lastNames.Add("Benson");
        lastNames.Add("Berry");
        lastNames.Add("Bishop");
        lastNames.Add("Black");
        lastNames.Add("Blair");
        lastNames.Add("Blake");
        lastNames.Add("Bott");
        lastNames.Add("Bowen");
        lastNames.Add("Bowman");
        lastNames.Add("Boyd");
        lastNames.Add("Bradley");
        lastNames.Add("Brady");
        lastNames.Add("Brewer");
        lastNames.Add("Brooks");
        lastNames.Add("Brown");
        lastNames.Add("Bryant");
        lastNames.Add("Burgess");
        lastNames.Add("Burke");
        lastNames.Add("Burns");
        lastNames.Add("Burton");
        lastNames.Add("Bush");
        lastNames.Add("Butler");
        lastNames.Add("Byrd");
        lastNames.Add("Cabrera");
        lastNames.Add("Calderon");
        lastNames.Add("Caldwell");
        lastNames.Add("Camacho");
        lastNames.Add("Campbell");
        lastNames.Add("Campos");
        lastNames.Add("Cannon");
        lastNames.Add("Cardenas");
        lastNames.Add("Carlson");
        lastNames.Add("Carpenter");
        lastNames.Add("Carr");
        lastNames.Add("Carrillo");
        lastNames.Add("Carroll");
        lastNames.Add("Carter");
        lastNames.Add("Castaneda");
        lastNames.Add("Castillo");
        lastNames.Add("Castro");
        lastNames.Add("Cervantes");
        lastNames.Add("Chambers");
        lastNames.Add("Chan");
        lastNames.Add("Chandler");
        lastNames.Add("Chang");
        lastNames.Add("Chapman");
        lastNames.Add("Chavez");
        lastNames.Add("Chen");
        lastNames.Add("Chiles");
        lastNames.Add("Christensen");
        lastNames.Add("Clark");
        lastNames.Add("Clarke");
        lastNames.Add("Cohen");
        lastNames.Add("Cole");
        lastNames.Add("Coleman");
        lastNames.Add("Collins");
        lastNames.Add("Colon");
        lastNames.Add("Contreras");
        lastNames.Add("Cook");
        lastNames.Add("Cooper");
        lastNames.Add("Cortez");
        lastNames.Add("Cox");
        lastNames.Add("Craig");
        lastNames.Add("Crawford");
        lastNames.Add("Cross");
        lastNames.Add("Cruz");
        lastNames.Add("Cummings");
        lastNames.Add("Cunningham");
        lastNames.Add("Curry");
        lastNames.Add("Curtis");
        lastNames.Add("Daniel");
        lastNames.Add("Daniels");
        lastNames.Add("Davidson");
        lastNames.Add("Davis");
        lastNames.Add("Dawson");
        lastNames.Add("Day");
        lastNames.Add("Dean");
        lastNames.Add("Delacruz");
        lastNames.Add("Deleon");
        lastNames.Add("Delgado");
        lastNames.Add("Dennis");
        lastNames.Add("Diaz");
        lastNames.Add("Dixon");
        lastNames.Add("Dominguez");
        lastNames.Add("Douglas");
        lastNames.Add("Doyle");
        lastNames.Add("Duncan");
        lastNames.Add("Dunn");
        lastNames.Add("Duran");
        lastNames.Add("Edwards");
        lastNames.Add("Elliott");
        lastNames.Add("Ellis");
        lastNames.Add("Erickson");
        lastNames.Add("Espinoza");
        lastNames.Add("Estrada");
        lastNames.Add("Evans");
        lastNames.Add("Fahy");
        lastNames.Add("Farmer");
        lastNames.Add("Ferguson");
        lastNames.Add("Fernandez");
        lastNames.Add("Fields");
        lastNames.Add("Figueroa");
        lastNames.Add("Fischer");
        lastNames.Add("Fisher");
        lastNames.Add("Fitzgerald");
        lastNames.Add("Fleming");
        lastNames.Add("Fletcher");
        lastNames.Add("Flores");
        lastNames.Add("Ford");
        lastNames.Add("Foster");
        lastNames.Add("Fowler");
        lastNames.Add("Fox");
        lastNames.Add("Francis");
        lastNames.Add("Franco");
        lastNames.Add("Frank");
        lastNames.Add("Franklin");
        lastNames.Add("Frazier");
        lastNames.Add("Freeman");
        lastNames.Add("Fuentes");
        lastNames.Add("Fuller");
        lastNames.Add("Gallagher");
        lastNames.Add("Gallegos");
        lastNames.Add("Garcia");
        lastNames.Add("Gardner");
        lastNames.Add("Garner");
        lastNames.Add("Garrett");
        lastNames.Add("Garza");
        lastNames.Add("George");
        lastNames.Add("Gibson");
        lastNames.Add("Gilbert");
        lastNames.Add("Gill");
        lastNames.Add("Gomez");
        lastNames.Add("Gonzales");
        lastNames.Add("Gonzalez");
        lastNames.Add("Goodman");
        lastNames.Add("Goodwin");
        lastNames.Add("Gordon");
        lastNames.Add("Graham");
        lastNames.Add("Grant");
        lastNames.Add("Graves");
        lastNames.Add("Gray");
        lastNames.Add("Green");
        lastNames.Add("Greene");
        lastNames.Add("Gregory");
        lastNames.Add("Griffin");
        lastNames.Add("Griffith");
        lastNames.Add("Gross");
        lastNames.Add("Guerra");
        lastNames.Add("Guerrero");
        lastNames.Add("Gutierrez");
        lastNames.Add("Guzman");
        lastNames.Add("Hail");
        lastNames.Add("Hale");
        lastNames.Add("Hall");
        lastNames.Add("Hamilton");
        lastNames.Add("Hammond");
        lastNames.Add("Hampton");
        lastNames.Add("Hansen");
        lastNames.Add("Hanson");
        lastNames.Add("Hardy");
        lastNames.Add("Harmon");
        lastNames.Add("Harper");
        lastNames.Add("Harrington");
        lastNames.Add("Harris");
        lastNames.Add("Harrison");
        lastNames.Add("Hart");
        lastNames.Add("Harvey");
        lastNames.Add("Hasshu");
        lastNames.Add("Hawkins");
        lastNames.Add("Hayes");
        lastNames.Add("Haynes");
        lastNames.Add("Hedges");
        lastNames.Add("Henderson");
        lastNames.Add("Henry");
        lastNames.Add("Hernandez");
        lastNames.Add("Herrera");
        lastNames.Add("Hicks");
        lastNames.Add("Higgins");
        lastNames.Add("Hill");
        lastNames.Add("Hines");
        lastNames.Add("Hodges");
        lastNames.Add("Hoffman");
        lastNames.Add("Holland");
        lastNames.Add("Holmes");
        lastNames.Add("Holt");
        lastNames.Add("Hopkins");
        lastNames.Add("Horton");
        lastNames.Add("Howard");
        lastNames.Add("Howell");
        lastNames.Add("Huang");
        lastNames.Add("Hubbard");
        lastNames.Add("Hudson");
        lastNames.Add("Hughes");
        lastNames.Add("Hunt");
        lastNames.Add("Hunter");
        lastNames.Add("Ingram");
        lastNames.Add("Jackson");
        lastNames.Add("Jacobs");
        lastNames.Add("James");
        lastNames.Add("Jenkins");
        lastNames.Add("Jennings");
        lastNames.Add("Jensen");
        lastNames.Add("Jimenez");
        lastNames.Add("Johnson");
        lastNames.Add("Johnston");
        lastNames.Add("Jones");
        lastNames.Add("Jordan");
        lastNames.Add("Joseph");
        lastNames.Add("Juarez");
        lastNames.Add("Keller");
        lastNames.Add("Kelley");
        lastNames.Add("Kelly");
        lastNames.Add("Kennedy");
        lastNames.Add("Khan");
        lastNames.Add("Kim");
        lastNames.Add("King");
        lastNames.Add("Klein");
        lastNames.Add("Knight");
        lastNames.Add("Kumru-Holroyd");
        lastNames.Add("Kypraios");
        lastNames.Add("Lambert");
        lastNames.Add("Lane");
        lastNames.Add("Lara");
        lastNames.Add("Larson");
        lastNames.Add("Lawrence");
        lastNames.Add("Lawson");
        lastNames.Add("Le");
        lastNames.Add("Lee");
        lastNames.Add("Leon");
        lastNames.Add("Leonard");
        lastNames.Add("Lewis");
        lastNames.Add("Li");
        lastNames.Add("Lin");
        lastNames.Add("Little");
        lastNames.Add("Liu");
        lastNames.Add("Logan");
        lastNames.Add("Long");
        lastNames.Add("Lopez");
        lastNames.Add("Love");
        lastNames.Add("Lowe");
        lastNames.Add("Lucas");
        lastNames.Add("Luna");
        lastNames.Add("Lynch");
        lastNames.Add("Lyons");
        lastNames.Add("Mack");
        lastNames.Add("Maldonado");
        lastNames.Add("Malone");
        lastNames.Add("Mann");
        lastNames.Add("Manning");
        lastNames.Add("Marquez");
        lastNames.Add("Marshall");
        lastNames.Add("Martin");
        lastNames.Add("Martinez");
        lastNames.Add("Mason");
        lastNames.Add("Matthews");
        lastNames.Add("Maxwell");
        lastNames.Add("May");
        lastNames.Add("McCarthy");
        lastNames.Add("Mccoy");
        lastNames.Add("Mcdaniel");
        lastNames.Add("McDonald");
        lastNames.Add("McGee");
        lastNames.Add("McKinney");
        lastNames.Add("McLaughlin");
        lastNames.Add("Medina");
        lastNames.Add("Meijer");
        lastNames.Add("Mejia");
        lastNames.Add("Mendez");
        lastNames.Add("Mendoza");
        lastNames.Add("Meyer");
        lastNames.Add("Miles");
        lastNames.Add("Miller");
        lastNames.Add("Mills");
        lastNames.Add("Miranda");
        lastNames.Add("Mitchell");
        lastNames.Add("Molina");
        lastNames.Add("Montgomery");
        lastNames.Add("Montoya");
        lastNames.Add("Moore");
        lastNames.Add("Morales");
        lastNames.Add("Moran");
        lastNames.Add("Moreno");
        lastNames.Add("Morgan");
        lastNames.Add("Morris");
        lastNames.Add("Morrison");
        lastNames.Add("Moss");
        lastNames.Add("Mullins");
        lastNames.Add("Munoz");
        lastNames.Add("Murphy");
        lastNames.Add("Murray");
        lastNames.Add("Myers");
        lastNames.Add("Navarro");
        lastNames.Add("Neal");
        lastNames.Add("Nelson");
        lastNames.Add("Newman");
        lastNames.Add("Newton");
        lastNames.Add("Nguyen");
        lastNames.Add("Nichols");
        lastNames.Add("Norman");
        lastNames.Add("Norris");
        lastNames.Add("Nunez");
        lastNames.Add("Obrien");
        lastNames.Add("Ochoa");
        lastNames.Add("Oconnor");
        lastNames.Add("Oliver");
        lastNames.Add("Olson");
        lastNames.Add("Ortega");
        lastNames.Add("Ortiz");
        lastNames.Add("Owens");
        lastNames.Add("Pacheco");
        lastNames.Add("Padilla");
        lastNames.Add("Page");
        lastNames.Add("Palmer");
        lastNames.Add("Park");
        lastNames.Add("Parker");
        lastNames.Add("Parks");
        lastNames.Add("Parsons");
        lastNames.Add("Patel");
        lastNames.Add("Patterson");
        lastNames.Add("Paul");
        lastNames.Add("Payne");
        lastNames.Add("Pearson");
        lastNames.Add("Pena");
        lastNames.Add("Perez");
        lastNames.Add("Perkins");
        lastNames.Add("Perry");
        lastNames.Add("Person");
        lastNames.Add("Peters");
        lastNames.Add("Peterson");
        lastNames.Add("Pham");
        lastNames.Add("Phillips");
        lastNames.Add("Pierce");
        lastNames.Add("Porter");
        lastNames.Add("Potter");
        lastNames.Add("Powell");
        lastNames.Add("Powers");
        lastNames.Add("Price");
        lastNames.Add("Quinn");
        lastNames.Add("Ramirez");
        lastNames.Add("Ramos");
        lastNames.Add("Ramsey");
        lastNames.Add("Ray");
        lastNames.Add("Reed");
        lastNames.Add("Reese");
        lastNames.Add("Reeves");
        lastNames.Add("Reid");
        lastNames.Add("Reyes");
        lastNames.Add("Reynolds");
        lastNames.Add("Rhodes");
        lastNames.Add("Rice");
        lastNames.Add("Richards");
        lastNames.Add("Richardson");
        lastNames.Add("Riley");
        lastNames.Add("Rios");
        lastNames.Add("Rivas");
        lastNames.Add("Rivera");
        lastNames.Add("Robbins");
        lastNames.Add("Roberts");
        lastNames.Add("Robertson");
        lastNames.Add("Robinson");
        lastNames.Add("Robles");
        lastNames.Add("Rodgers");
        lastNames.Add("Rodriguez");
        lastNames.Add("Rogers");
        lastNames.Add("Rojas");
        lastNames.Add("Roman");
        lastNames.Add("Romero");
        lastNames.Add("Rosales");
        lastNames.Add("Rose");
        lastNames.Add("Ross");
        lastNames.Add("Rowe");
        lastNames.Add("Ruiz");
        lastNames.Add("Russell");
        lastNames.Add("Ryan");
        lastNames.Add("Salazar");
        lastNames.Add("Salinas");
        lastNames.Add("Sanchez");
        lastNames.Add("Sanders");
        lastNames.Add("Sandoval");
        lastNames.Add("Santiago");
        lastNames.Add("Santos");
        lastNames.Add("Saunders");
        lastNames.Add("Schmidt");
        lastNames.Add("Schneider");
        lastNames.Add("Schroeder");
        lastNames.Add("Schultz");
        lastNames.Add("Schwartz");
        lastNames.Add("Scott");
        lastNames.Add("Serrano");
        lastNames.Add("Sharp");
        lastNames.Add("Shaw");
        lastNames.Add("Shell");
        lastNames.Add("Shelton");
        lastNames.Add("Sherman");
        lastNames.Add("Silva");
        lastNames.Add("Simmons");
        lastNames.Add("Simon");
        lastNames.Add("Simpson");
        lastNames.Add("Sims");
        lastNames.Add("Singh");
        lastNames.Add("Smith");
        lastNames.Add("Snyder");
        lastNames.Add("Solis");
        lastNames.Add("Soto");
        lastNames.Add("Spencer");
        lastNames.Add("Stanley");
        lastNames.Add("Steele");
        lastNames.Add("Stephens");
        lastNames.Add("Stevens");
        lastNames.Add("Stevenson");
        lastNames.Add("Stewart");
        lastNames.Add("Stone");
        lastNames.Add("Strain");
        lastNames.Add("Strickland");
        lastNames.Add("Sullivan");
        lastNames.Add("Sutton");
        lastNames.Add("Swanson");
        lastNames.Add("Tate");
        lastNames.Add("Taylor");
        lastNames.Add("Terry");
        lastNames.Add("Thomas");
        lastNames.Add("Thompson");
        lastNames.Add("Thornton");
        lastNames.Add("Todd");
        lastNames.Add("Torres");
        lastNames.Add("Townsend");
        lastNames.Add("Tran");
        lastNames.Add("Trujillo");
        lastNames.Add("Tucker");
        lastNames.Add("Turner");
        lastNames.Add("Valdez");
        lastNames.Add("Valencia");
        lastNames.Add("Vargas");
        lastNames.Add("Vasquez");
        lastNames.Add("Vaughn");
        lastNames.Add("Vazquez");
        lastNames.Add("Vega");
        lastNames.Add("Velasquez");
        lastNames.Add("Wade");
        lastNames.Add("Wagner");
        lastNames.Add("Walker");
        lastNames.Add("Wallace");
        lastNames.Add("Walsh");
        lastNames.Add("Walters");
        lastNames.Add("Walton");
        lastNames.Add("Wang");
        lastNames.Add("Ward");
        lastNames.Add("Warner");
        lastNames.Add("Warren");
        lastNames.Add("Washington");
        lastNames.Add("Waters");
        lastNames.Add("Watkins");
        lastNames.Add("Watson");
        lastNames.Add("Watts");
        lastNames.Add("Weaver");
        lastNames.Add("Webb");
        lastNames.Add("Weber");
        lastNames.Add("Webster");
        lastNames.Add("Welch");
        lastNames.Add("Wells");
        lastNames.Add("West");
        lastNames.Add("Wheeler");
        lastNames.Add("White");
        lastNames.Add("Williams");
        lastNames.Add("Williamson");
        lastNames.Add("Willis");
        lastNames.Add("Wilson");
        lastNames.Add("Wise");
        lastNames.Add("Wolf");
        lastNames.Add("Wolfe");
        lastNames.Add("Wong");
        lastNames.Add("Wood");
        lastNames.Add("Woods");
        lastNames.Add("Wright");
        lastNames.Add("Wu");
        lastNames.Add("Yang");
        lastNames.Add("Young");
        lastNames.Add("Zhang");
        lastNames.Add("Zimmerman");
        #endregion
    }
}
